apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-fraud
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Postgres
    uid: postgres-fraud
    type: postgres
    access: proxy
    url: postgres:5432
    user: fraud
    secureJsonData:
      password: fraud
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      database: fraud
    editable: false
